name: 🚧 Linux | Run harvest tests

on:
  workflow_call:

env:
  GO_VERSION: '1.19.3'

jobs:
  test:
    name: Linux harvest tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{env.GO_VERSION}}

      - name: go version
        run: go version

      - name: which go
        run: which go

      - name: sudo go version
        run: sudo -E go version

      - run: |
          # https://github.com/actions/setup-go/issues/107
          cp -f `which go` /usr/bin/go

      - name: sudo go version
        run: sudo -E go version

      - name: sudo /usr/bin/go version
        run: sudo -E /usr/bin/go version

      - name: Setup node
        run: sudo apt install musl-dev

      - name: Go env
        run: go env

      - name: Sudo Go env
        run: sudo -E go env

      - name: Sudo Go env 2
        run: sudo env GOROOT=$GOROOT go env

      - name: Running Harvest tests
        run: sudo make linux/harvest-tests

      - name: Running Harvest tests
        run: sudo -E make linux/harvest-tests
